/*---------------------------------------------------------------------------------
ESTRUCTURAS DE DATOS	GPO:3P2

APROXIMACION AL NUMERO DE EULER IMPLEMENTANDO RECURSIVIDAD Y DIVICIONES CONTINUAS

ORELLAN SILVA LUIS ADOLFO MATEO  16011190

PROFESOR: M.C. ALEJANDRO AGUILAR
---------------------------------------------------------------------------------*/

#include<iostream> 

using namespace std;	  //IMPLEMENTACION DEL ESPACIO DE NOMBRES std PARA PODER USAR LAS FUNCIONES cout Y cin LOCALIZADAS EN LA LIBREARIA iostream

int i=0;			//VARIABLE i ALMACENRA EL NUMERO MAXIMO DE ITERACIONES PARA LA FUNCION Euler
int a=0;			//VARIABLE a ALMACENRA EL VALOR QUE SE SUMA A LA DIVICION EN CADA ITERACION
int x=2;			//VARIABLE x SE USARA PARA ASIGNAR VALORES A LA VARIABLE a, 2,4,6,8,...,2n,...etc

//DEFINICION DE LA FUNCION Euler LA CUAL DARA UNA APROXIMACION AL VALOR DEL Numero De Euler(e=2.718281828459045235360...)
double Euler(int n)		//EL PARAMETRO n CONTROLARA EL NUMERO DE ITERACIONES EL CUAL IRA EN DECREMENTO
{
	////////////////////////////////
	//CONDICIONES QUE DETERMINAN EL VALOR DE a EN LA SERIE [2;1,2,1,1,4,1,1,6,1,1,8,1,1,...,2n,1,1,...]
	
	if(n==i)		//CONDICION QUE ASIGNA A LA VARIABLE a EL VALOR INCIAL DE LA SERIE (2)
	{
		a=2;		
	}
	else if(n>=1&&n<i&&n%3==0) //CONDICION QUE ASIGNA A LA VARIABLE a LOS VALORES PARES DE LA SERIE (2,4,6,etc)
	{
		a=x;
		x+=2;
	}
	else		//CONDICION QUE ASIGNA A LA VARIABLE a EL VALOR DE 1 SOLO SI NO CUMPLE NINGUNA DE LAS CONDICIONES ANTERIORES
	{
		a=1;
	}
	/////////////////////////////////////////
	
	if(n==1)	//CONDICION DE PARADA DE LA RECURSIVIDAD
	{
		return 1;	//SI EL VALOR DE n ES IGUAL A 1 ENTONSES SE RETORNARA 1
	}
	else
	{
		//cout<<a<<endl;			  //IMRIME EL VALOR DE a EN CADA ITERACION, PERMITIENDO IDENTIFICAR ERRORES EN LA SERIE
		return a+1/Euler(n-1);		//DEFINICION DE LA FRACCION CONTINUA
	}
}//FIN DE LA DEFINICION DE LA FUNCION Euler

int main()
{
	cin>>i;				//LEE EL VALOR INGRESADO POR EL USUARIO Y LO ALMACENA EN i
	cout<<Euler(i);		//LLAMA E IMPRIME EL VALOR RETORNADO DE LA FUNCION Euler CON LA VARIABLE i COMO PARAMETRO
	
	cin.get();	cin.get();		//ESPERA A QUE EL USUARIO OPRIMA UNA TECLA PARA FINALIZAR EL PROGRAMA
}
